production:
  solr:
    hostname: <%= ENV['SOLR_URL']%>
    port: <%= ENV['SOLR_PORT']%>
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: DEBUG

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING